language: python
python:
  - "3.6"

jobs:
  include:
    - stage: deploy
      script:
        # install nvm
        - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
        - source ~/.nvm/nvm.sh
        - nvm install lts/*
        - npm install -g @semantic-release/exec semantic-release
        - pip install bumpversion
        - semantic-release
          
install:
  - pip install .[test]
script:
  - pytest