language: python
python:
  - "3.6"

jobs:
  include:
    - stage: release
      deploy:
        provider: script
        skip_cleanup: true
        script:
          # install nvm
          - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
          - source ~/.nvm/nvm.sh
          - nvm install lts/*
          - npx semantic-release
        on:
          all_branches: true
          
install:
  - pip install .[test]
script:
  - pytest