language: python
python:
  - "3.6"

jobs:
  include:
    - stage: deploy
      script:
        - nvm install lts/*
        - npm install -g semantic-release @semantic-release/exec @semantic-release/git
        - pip install bumpversion
        - semantic-release
          
install:
  - pip install .[test]
script:
  - pytest